title: Max Chadwick
url: http://maxchadwick.xyz
permalink: /blog/:title
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:
  - octopress-autoprefixer

excerpt_separator: <!-- excerpt_separator -->
