title: Max Chadwick
url: https://maxchadwick.xyz
permalink: /blog/:title
markdown: kramdown
paginate: 6
paginate_path: "/blog/:num/"
author: "Max Chadwick"

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

gems:
  - octopress-autoprefixer
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

excerpt_separator: <!-- excerpt_separator -->
