title: Max Chadwick
url: http://maxchadwick.xyz
permalink: /blog/:title
markdown: kramdown
paginate: 5
paginate_path: "/blog/:num/"

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:
  - octopress-autoprefixer
  - jekyll-paginate
  - jekyll-feed

excerpt_separator: <!-- excerpt_separator -->
