title: Max Chadwick
url: https://maxchadwick.xyz
permalink: /blog/:title
markdown: kramdown
paginate: 6
paginate_path: "/blog/:num/"

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:
  - octopress-autoprefixer
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

excerpt_separator: <!-- excerpt_separator -->
