author: "Max Chadwick"
url: http://localhost:4000
excerpt_separator: <!-- excerpt_separator -->
markdown: kramdown
paginate: 6
paginate_path: "/blog/:num/"
future: true

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
